//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JKDataEntities : DbContext
    {
        public JKDataEntities()
            : base("name=JKDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorityFunction> AuthorityFunction { get; set; }
        public virtual DbSet<AuthorityRole> AuthorityRole { get; set; }
        public virtual DbSet<AuthorityRoleInFunction> AuthorityRoleInFunction { get; set; }
        public virtual DbSet<AuthorityUserInRole> AuthorityUserInRole { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserAccountWechat> UserAccountWechat { get; set; }
        public virtual DbSet<UserLoginRecords> UserLoginRecords { get; set; }
        public virtual DbSet<UserOperationRecords> UserOperationRecords { get; set; }
        public virtual DbSet<WechatPayNotify> WechatPayNotify { get; set; }
        public virtual DbSet<WechatPayRecords> WechatPayRecords { get; set; }
        public virtual DbSet<WechatPayRefundNotify> WechatPayRefundNotify { get; set; }
        public virtual DbSet<WechatPayRefundRecords> WechatPayRefundRecords { get; set; }
    }
}
