//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryPrize
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public System.Guid PrizeActivityGuid { get; set; }
        public string PrizeType { get; set; }
        public string PrizeName { get; set; }
        public int Money { get; set; }
        public int TotalNum { get; set; }
        public int WinningRate { get; set; }
        public string DefaultPic { get; set; }
        public string Detail { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public int Grade { get; set; }
    
        public virtual LotteryActivity LotteryActivity { get; set; }
    }
}
