//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyLotteryV
    {
        public string Title { get; set; }
        public string Type { get; set; }
        public string DefaultPic { get; set; }
        public int BaseNumber { get; set; }
        public string Detail { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.Guid PrizeActivityGuid { get; set; }
        public System.Guid UserGuid { get; set; }
        public bool IsWenner { get; set; }
        public System.Guid PrizeGuid { get; set; }
        public string PrizeName { get; set; }
        public Nullable<int> Money { get; set; }
        public string PrizeType { get; set; }
        public string PrizePic { get; set; }
        public string PrizeDetail { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
