//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEvaluation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderEvaluation()
        {
            this.OrderEvaluationPic = new HashSet<OrderEvaluationPic>();
        }
    
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public System.Guid OrderGuid { get; set; }
        public System.Guid ProductGuid { get; set; }
        public string ProductName { get; set; }
        public System.Guid ClassificationGuid { get; set; }
        public string ClassificationName { get; set; }
        public System.Guid UserGuid { get; set; }
        public string UserName { get; set; }
        public string UserNickName { get; set; }
        public int DescriptionOfGoodGrade { get; set; }
        public int LogisticsGrade { get; set; }
        public bool IsAnonymous { get; set; }
        public bool IsSystemEvaluated { get; set; }
        public string EvaluationContent { get; set; }
        public bool IsDisplay { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvaluationPic> OrderEvaluationPic { get; set; }
    }
}
