//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderEvaluation = new HashSet<OrderEvaluation>();
            this.OrderProduct = new HashSet<OrderProduct>();
            this.OrderRefund = new HashSet<OrderRefund>();
        }
    
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public int OrderAmount { get; set; }
        public System.Guid UserGuid { get; set; }
        public string UserName { get; set; }
        public string UserNickName { get; set; }
        public System.Guid DeliveryAddressGuid { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public string ReceiverName { get; set; }
        public string Phone { get; set; }
        public string DeliveryAddress { get; set; }
        public System.Guid ShippingGuid { get; set; }
        public string ShipperName { get; set; }
        public string LogisticsCode { get; set; }
        public string ShippingRemark { get; set; }
        public string OrderRemark { get; set; }
        public string PaymentType { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime PayTime { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public System.DateTime FinishedTime { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public bool IsEvaluated { get; set; }
        public System.Guid StoreGuid { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvaluation> OrderEvaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRefund> OrderRefund { get; set; }
    }
}
