//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEvalutionReply
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public System.Guid EvaluationGuid { get; set; }
        public string Replier { get; set; }
        public string ReplyContent { get; set; }
        public bool IsSystem { get; set; }
        public bool IsDisplay { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
