//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRefund
    {
        public System.Guid Guid { get; set; }
        public string RefundNo { get; set; }
        public System.Guid UserGuid { get; set; }
        public System.Guid OrderProductGuid { get; set; }
        public System.Guid OrderGuid { get; set; }
        public System.Guid ProductGuid { get; set; }
        public System.Guid ClassificationGuid { get; set; }
        public int RefundAmount { get; set; }
        public string RefundRemark { get; set; }
        public string CheckRefundRemark { get; set; }
        public System.DateTime RefundSuccessTime { get; set; }
        public string Status { get; set; }
        public System.DateTime CheckRefundTime { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductClassification ProductClassification { get; set; }
    }
}
