//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductClassification()
        {
            this.OrderRefund = new HashSet<OrderRefund>();
        }
    
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public System.Guid ProductGuid { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public decimal Grams { get; set; }
        public int Price { get; set; }
        public int PromotionPrice { get; set; }
        public string PicUrl { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRefund> OrderRefund { get; set; }
        public virtual Product Product { get; set; }
    }
}
