//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountWechat
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public System.Guid UserAccountGuid { get; set; }
        public string WechatOpenId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Sex { get; set; }
        public string Country { get; set; }
        public string WechatNickName { get; set; }
        public string WechatAvatarImgUrl { get; set; }
        public string Privilege { get; set; }
        public string Unionid { get; set; }
        public string SessionKey { get; set; }
        public System.Guid RecommenderGuid { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
