//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WechatPayRefundRecords
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public string NonceStr { get; set; }
        public string Sign { get; set; }
        public string SignType { get; set; }
        public string TransactionId { get; set; }
        public string OutTradeNo { get; set; }
        public string OutRefundNo { get; set; }
        public int TotalFee { get; set; }
        public int RefundFee { get; set; }
        public string RefundFeeType { get; set; }
        public string RefundDesc { get; set; }
        public string ReturnCode { get; set; }
        public string ReturnMsg { get; set; }
        public string ResultCode { get; set; }
        public string ErrCode { get; set; }
        public string ErrCodeDes { get; set; }
        public string Appid { get; set; }
        public string MchId { get; set; }
        public string RefundId { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
