//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WechatPayRecords
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public System.Guid OrderGuid { get; set; }
        public string OrderNo { get; set; }
        public System.Guid UserGuid { get; set; }
        public string UserOpenId { get; set; }
        public string SpbillCreateIP { get; set; }
        public int TotalFee { get; set; }
        public string Body { get; set; }
        public string ProductId { get; set; }
        public string NonceStr { get; set; }
        public string TradeType { get; set; }
        public string ReturnCode { get; set; }
        public string ReturnMsg { get; set; }
        public string ResultCode { get; set; }
        public string ResultSign { get; set; }
        public string ErrCode { get; set; }
        public string ErrCodeDes { get; set; }
        public string PrepayId { get; set; }
        public string CodeUrl { get; set; }
        public System.DateTime TimeUpdate { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
