//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawCashOrder
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public System.Guid UserGuid { get; set; }
        public int Money { get; set; }
        public bool IsChecked { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public System.DateTime TimeCretead { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
